[package]
name = "tokio-workq"
version = "0.1.0"
authors = ["Hideo Hattori <hattori-h@klab.com>"]

[dependencies]
futures = "0.1"
tokio-core = "0.1"
tokio-line = { git = "https://github.com/tokio-rs/tokio-line" }
